apiVersion: v1
kind: Service
metadata:
  name: statsd-exporter
  labels:
    {{- include "lightstep.labels" . | nindent 4 }}
spec:
{{ if .Values.service.metricExporter }}
  type: {{ .Values.service.metricServiceType }}
{{ end }}
  ports:
    - name: prom-endpoint
      port: {{ .Values.service.promScrapeEndpoint }}
      targetPort: {{.Values.promScrapeEndpoint}}
  selector:
    {{- include "lightstep.selectorLabels" . | nindent 4 }}